### PR TITLE
Add plugin for automatically populating teams based on contributors

### PR DESCRIPTION
**Pull request by astrofrog**
:warning: Don't merge, as this currently has potential security issues ⚠️ 

*This is a follow up on #53 and should be rebased once that PR is merged*

This PR adds a new plugin that can be used to auto add GitHub users to teams based on contributors to a repository. In practice, this could be used for example in astropy to add any contributors to the core, infrastructure, and coordinated packages to the 'astropy contributors' team which has no write access but can be used for assigning people to issues/pull requests. The bot would need to be installed on any repository that would want this behavior.

There is a moderate security issue - essentially any repository where the bot is installed could start adding contributors to teams in the project that have write permissions on various repositories. Note that this is only possible if one of the owners of the GitHub organization adds the bot app to a repository, and only maintainers of those repositories can modify the ``pyproject.toml`` file - nevertheless, this means that anyone with write access to any coordinated, infrastructure, or the core repository can arbitrarily manage teams (even if they wouldn't otherwise have the permission to do so).

There are several options to resolve this:

- to not actually put this plugin here but instead put it in individual bot apps with teams hard-coded, e.g. 'astropy contributors'
- to only allow this plugin to add people to read-only teams
- to have a way of saying that some configuration items can only be read from the bot config, not the individual repo config

@Cadair @pllim @bsipocz - any thoughts?

(also thanks to @bsipocz for making me think about the security implications back in #53)

### CODE REVIEW

**Comment by pllim** [comment]
Better be safe than sorry. Maybe having the functionality in place but not automated is enough? Whoever wants to use it will have to run it manually (provided that person has a proper access)? A "dry run" or "are you sure" option for `update_team_on_push` would be nice too -- something to give whoever running this time to pause and think over the implications.

**Comment by bsipocz** [comment]
It seems GitHub is solving at least half of this issue for us. We can now assign people who have commented on said issue (I assume  PR,  too)
 https://github.blog/2019-06-25-assign-issues-to-issue-commenters/?utm_campaign=1561485263&utm_medium=social&utm_source=twitter&utm_content=1561485263

**Comment by bsipocz** [comment]
I think we can close this now, once someone is commented on an issue/PR they can be assigned, so no need to hack them in to a team.

**Comment by pllim** [comment]
I concur with @bsipocz .

**Pull request closed without merging**
